# Add application configuration variables here, as shown below.

ADMIN_EMAIL: you@yourdomain.com
ADMIN_PASS:  yoursecretpassword

CAP_DEPLOY_TO: /var/www/gif_app
CAP_SERVER: example.com
CAP_USER: deploy
CAP_CHRUBY: ruby-2.1.2

